---
- name: Toposes
  hosts: Toposes
  connection: local
  vars:
    pkg_dir: "~/.gap/pkg/"
    ansible_python_interpreter: "{{ansible_playbook_python}}"
  tasks:
    - import_tasks: tasks/package.yml
      vars:
        package:
          name: Toposes
          description: "Elementary toposes"
          doc_additional_latex_preamble: |
            \usepackage{mathtools}
          tests_only_basic: true
        ci_additional_packages_to_clone:
          - homalg_project
          - CAP_project
          - CategoryConstructor
          - SubcategoriesForCAP
          - Locales
          - ZariskiFrames
          - LazyCategories
          - FinSetsForCAP
          - HigherHomologicalAlgebra
          - QPA2
        ci_additional_packages_to_test:
          - Locales
          - ZariskiFrames
          - FinSetsForCAP
        ci_ubuntu_additional_apt_packages:
          - texlive-fonts-extra

- name: Locales
  hosts: Locales
  connection: local
  vars:
    pkg_dir: "~/.gap/pkg/"
    ansible_python_interpreter: "{{ansible_playbook_python}}"
  tasks:
    - import_tasks: tasks/package.yml
      vars:
        package:
          name: Locales
          description: "Locales, frames, coframes, meet semi-lattices of locally closed subsets, and Boolean algebras of constructible sets"
          has_HOMALG_IO: true
          doc_additional_latex_preamble: |
            \usepackage{mathtools}
          tests_additional_packages_to_load:
            - SubcategoriesForCAP
            - LazyCategories
          tests_only_basic: true
        ci_additional_packages_to_clone:
          - homalg_project
          - CAP_project
          - Toposes
          - CategoryConstructor
          - SubcategoriesForCAP
          - LazyCategories
        ci_ubuntu_additional_apt_packages:
          - texlive-fonts-extra

- name: ZariskiFrames
  hosts: ZariskiFrames
  connection: local
  vars:
    pkg_dir: "~/.gap/pkg/"
    ansible_python_interpreter: "{{ansible_playbook_python}}"
  tasks:
    - import_tasks: tasks/package.yml
      vars:
        package:
          name: ZariskiFrames
          description: "(Co)frames/Locales of Zariski closed/open subsets of affine, projective, or toric varieties"
          has_HOMALG_IO: true
          doc_additional_latex_preamble: |
            \usepackage{mathtools}
            \DeclareUnicodeCharacter{2205}{\O}
            \DeclareUnicodeCharacter{222A}{\ensuremath{\cup}}
            \DeclareUnicodeCharacter{22C3}{\ensuremath{\bigcup}}
            \DeclareUnicodeCharacter{2229}{\ensuremath{\cap}}
          tests_only_basic: true
        ci_additional_packages_to_clone:
          - homalg_project
          - CAP_project
          - Toposes
          - CategoryConstructor
          - Locales
          - FinSetsForCAP
          - HigherHomologicalAlgebra
          - QPA2
        ci_ubuntu_additional_apt_packages:
          - texlive-fonts-extra

- name: SubcategoriesForCAP
  hosts: SubcategoriesForCAP
  connection: local
  vars:
    pkg_dir: "~/.gap/pkg/"
    ansible_python_interpreter: "{{ansible_playbook_python}}"
  tasks:
    - import_tasks: tasks/package.yml
      vars:
        package:
          name: SubcategoriesForCAP
          description: "Subcategory and other related constructors for CAP categories"
          has_HOMALG_IO: true
          doc_additional_latex_preamble: |
            \usepackage{mathtools}
          tests_only_basic: true
        ci_additional_packages_to_clone:
          - homalg_project
          - CAP_project
          - CategoryConstructor
          - Toposes
          - FinSetsForCAP
          - HigherHomologicalAlgebra
          - QPA2
        ci_ubuntu_additional_apt_packages:
          - texlive-fonts-extra

- name: Algebroids
  hosts: Algebroids
  connection: local
  vars:
    pkg_dir: "~/.gap/pkg/"
    ansible_python_interpreter: "{{ansible_playbook_python}}"
  tasks:
    - import_tasks: tasks/package.yml
      vars:
        package:
          name: Algebroids
          description: "Algebroids and bialgebroids as preadditive categories generated by enhanced quivers"
          has_HOMALG_IO: true
          doc_additional_latex_preamble: |
            \usepackage{mathtools}
          tests_only_basic: true
        ci_additional_packages_to_clone:
          - homalg_project
          - CAP_project
          - CategoryConstructor
          - FunctorCategories
          - HigherHomologicalAlgebra
          - QPA2
        ci_ubuntu_additional_apt_packages:
          - texlive-fonts-extra

- name: FunctorCategories
  hosts: FunctorCategories
  connection: local
  vars:
    pkg_dir: "~/.gap/pkg/"
    ansible_python_interpreter: "{{ansible_playbook_python}}"
  tasks:
    - import_tasks: tasks/package.yml
      vars:
        package:
          name: FunctorCategories
          description: "Categories of functors"
          doc_additional_latex_preamble: |
            \usepackage{mathtools}
        ci_additional_packages_to_clone:
          - homalg_project
          - CAP_project
          - HigherHomologicalAlgebra
          - QPA2
          - Algebroids
          - CategoryConstructor
        ci_ubuntu_additional_apt_packages:
          - texlive-fonts-extra

- name: InternalModules
  hosts: InternalModules
  connection: local
  vars:
    pkg_dir: "~/.gap/pkg/"
  tasks:
    - import_tasks: tasks/package.yml
      vars:
        package:
          name: InternalModules
          description: "Modules over internal algebras"
          has_HOMALG_IO: true
          doc_additional_latex_preamble: |
            \usepackage{bbm}
            \DeclareUnicodeCharacter{1D7D9}{\ensuremath{\mathbbm{1}}}
            \DeclareUnicodeCharacter{03C3}{\ensuremath{\sigma}}
            \DeclareUnicodeCharacter{03C1}{\ensuremath{\rho}}
            \DeclareUnicodeCharacter{03BD}{\ensuremath{\nu}}
            \DeclareUnicodeCharacter{03C7}{\ensuremath{\chi}}
        ci_additional_packages_to_clone:
          - homalg_project
          - CAP_project
          - InfiniteLists
          - GradedCategories
        ci_ubuntu_additional_apt_packages:
          - texlive-fonts-extra

- name: GradedCategories
  hosts: GradedCategories
  connection: local
  vars:
    pkg_dir: "~/.gap/pkg/"
  tasks:
    - import_tasks: tasks/package.yml
      vars:
        package:
          name: GradedCategories
          description: "Graded closures of categories"
          has_HOMALG_IO: true
        ci_additional_packages_to_clone:
          - homalg_project
          - CAP_project
          - InfiniteLists
          - InternalModules
        ci_additional_packages_to_test:
          - InternalModules
        ci_ubuntu_additional_apt_packages:
          - texlive-fonts-extra

- name: FinSetsForCAP
  hosts: FinSetsForCAP
  connection: local
  vars:
    pkg_dir: "~/.gap/pkg/"
  tasks:
    - import_tasks: tasks/package.yml
      vars:
        package:
          name: FinSetsForCAP
          description: "The elementary topos of (skeletal) finite sets"
        ci_additional_packages_to_clone:
          - homalg_project
          - CAP_project
          - Toposes

- name: FinGSetsForCAP
  hosts: FinGSetsForCAP
  connection: local
  vars:
    pkg_dir: "~/.gap/pkg/"
  tasks:
    - import_tasks: tasks/package.yml
      vars:
        package:
          name: FinGSetsForCAP
          description: "The elementary topos of (skeletal) finite G-sets"
          doc_additional_latex_preamble: |
            \usepackage[T1]{fontenc}
            \usepackage[british]{babel}
            \usepackage{microtype}
            \usepackage{amsmath}
            \usepackage{calc}
            \usepackage{amsthm}
            \usepackage{amssymb}
            \usepackage[dvipsnames]{xcolor}
            \usepackage{hyperref}
            \usepackage[linesnumbered,ruled,vlined]{algorithm2e}
            \usepackage{cite}
            \usepackage{url}
            \usepackage{tikz}
            \usetikzlibrary{shapes,arrows,matrix}
            \usepackage{tikz-cd}
            \usepackage{makeidx}
            \usepackage{listings}
            \usepackage[scaled]{beramono}
            \usepackage[figure]{hypcap}
            \renewcommand{\hypcapspace}{2\baselineskip}
            \usepackage{mathtools}
            \usepackage{faktor}
            \DeclareMathOperator{\Stab}{Stab}
            \DeclareMathOperator{\fix}{fix}
            \DeclareMathOperator{\coeq}{coeq}
            \DeclareMathOperator{\im}{im}
            \DeclareMathOperator{\rank}{rank}
            \DeclareMathOperator{\CartProdExt}{CartProdExt}
            \DeclareMathOperator{\End}{End}
            \DeclareMathOperator{\Hom}{Hom}
            \DeclareMathOperator{\op}{op}
            \DeclareMathOperator{\id}{id}
            \DeclareMathOperator{\Obj}{Obj}
            \usepackage{ifthen}
            % use \ell instead of l everywhere
            \mathcode`l="8000
            \begingroup
            \makeatletter
            \lccode`\~=`\l
            \DeclareMathSymbol{\lsb@l}{\mathalpha}{letters}{`l}
            \lowercase{\gdef~{\ifnum\the\mathgroup=\m@ne \ell \else \lsb@l \fi}}%
            \endgroup
        ci_additional_packages_to_clone:
          - homalg_project
          - CAP_project
          - Toposes
          - FinSetsForCAP
        ci_ubuntu_additional_apt_packages:
          - texlive-science
          - texlive-fonts-extra

- name: CAP_project
  hosts: CAP_project
  connection: local
  vars:
    pkg_dir: "~/.gap/pkg/"
  tasks:
    - import_tasks: tasks/meta_package.yml
      vars:
        meta_package:
          name: CAP_project
          description: Categories, Algorithms, and Programming
        subpackages:
          - name: CAP
            description: Categories, Algorithms, Programming
            has_HOMALG_IO: true
            doc_additional_latex_preamble: |
              \usepackage{tikz}
              \usetikzlibrary{arrows}
              \pgfarrowsdeclarecombine{twohead}{twohead}{latex}{latex}{latex}{latex}
            tests_additional_packages_to_load:
              - IO_ForHomalg
              - GaussForHomalg
              - ModulePresentationsForCAP
              - LinearAlgebraForCAP
              - RingsForHomalg
              - HomologicalAlgebraForCAP
              - DeductiveSystemForCAP
            tests_only_basic: true
          - name: CompilerForCAP
            description: Speed up computations in CAP categories
            doc_additional_latex_preamble: |
              % this is the only way to suppress an overfull hbox in the signature of CapJitIterateOverTree
              \geometry{left=26mm,right=26mm}
            tests_additional_packages_to_load:
              - LinearAlgebraForCAP
              - RingsForHomalg
          - name: ModulePresentationsForCAP
            docu_only: true
          - name: GradedModulePresentationsForCAP
            docu_only: true
          - name: LinearAlgebraForCAP
            docu_only: true
          - name: GeneralizedMorphismsForCAP
            docu_only: true
          - name: GroupRepresentationsForCAP
            description: Skeletal category of group representations for CAP
            has_HOMALG_IO: true
            tests_additional_packages_to_load:
              - IO_ForHomalg
            tests_only_basic: true
          - name: InternalExteriorAlgebraForCAP
            docu_only: true
          - name: MonoidalCategories
            description: Monoidal and monoidal (co)closed categories
            tests_additional_packages_to_load:
              - MatricesForHomalg
              - GaussForHomalg
            tests_only_basic: true
            docu_only: true
          - name: FreydCategoriesForCAP
            description: Freyd categories - Formal (co)kernels for additive categories
            has_HOMALG_IO: true
            doc_additional_scan_dirs:
              - gap/CategoryOfGradedRowsAndColumns
              - gap/GradedModulePresentationsByFreyd
            doc_additional_latex_preamble: |
              \usepackage{tikz}
              \usetikzlibrary{arrows}
              \usetikzlibrary{calc}
            tests_additional_packages_to_load:
              - IO_ForHomalg
              - RingsForHomalg
              - GaussForHomalg
              - GeneralizedMorphismsForCAP
              - Algebroids
            tests_only_basic: true
            docu_only: true
        ci_additional_packages_to_clone:
          - homalg_project
        ci_ubuntu_additional_apt_packages:
          - texlive-science

- name: homalg_project
  hosts: homalg_project
  connection: local
  vars:
    pkg_dir: "~/.gap/pkg/"
  tasks:
    - import_tasks: tasks/meta_package.yml
      vars:
        meta_package:
          name: homalg_project
          description: The packages of the homalg project
        subpackages:
          - name: homalg
            docu_only: true
          - name: 4ti2Interface
            docu_only: true
          - name: ExamplesForHomalg
            docu_only: true
          - name: Gauss
            docu_only: true
          - name: GaussForHomalg
            docu_only: true
          - name: GradedModules
            docu_only: true
          - name: GradedRingForHomalg
            docu_only: true
          - name: HomalgToCAS
            docu_only: true
          - name: IO_ForHomalg
            docu_only: true
          - name: LocalizeRingForHomalg
            docu_only: true
          - name: MatricesForHomalg
            docu_only: true
          - name: Modules
            docu_only: true
          - name: RingsForHomalg
            docu_only: true
          - name: SCO
            docu_only: true
          - name: ToolsForHomalg
            docu_only: true
        ci_ubuntu_additional_apt_packages:
          - texlive-science
          - time
          - python-pathlib
