---
- name: localhost
  hosts: localhost
  connection: local
  vars:
    pkg_dir: "~/.gap/pkg/"
  tasks:
    - import_tasks: tasks/package.yml
      vars:
        package_name: InternalModules
        package_description: "Modules over internal algebras"
        ci_additional_packages:
          - homalg_project
          - CAP_project
          - InfiniteLists
          - GradedCategories
        ci_ubuntu_additional_apt_packages:
          - texlive-fonts-extra
        additional_latex_preamble: |
          \usepackage{bbm}
          \DeclareUnicodeCharacter{1D7D9}{\ensuremath{\mathbbm{1}}}
          \DeclareUnicodeCharacter{03C3}{\ensuremath{\sigma}}
          \DeclareUnicodeCharacter{03C1}{\ensuremath{\rho}}
          \DeclareUnicodeCharacter{03BD}{\ensuremath{\nu}}
          \DeclareUnicodeCharacter{03C7}{\ensuremath{\chi}}
    - import_tasks: tasks/package.yml
      vars:
        package_name: GradedCategories
        package_description: "Graded closures of categories"
        ci_additional_packages:
          - homalg_project
          - CAP_project
          - InfiniteLists
          - InternalModules
        ci_ubuntu_additional_apt_packages:
          - texlive-fonts-extra
    - import_tasks: tasks/package.yml
      vars:
        package_name: FinSetsForCAP
        package_description: "The elementary topos of (skeletal) finite sets"
        ci_additional_packages:
          - homalg_project
          - CAP_project
          - Toposes
