---
- name: localhost
  hosts: localhost
  connection: local
  vars:
    pkg_dir: "~/.gap/pkg/"
  tasks:
    - import_tasks: tasks/package.yml
      vars:
        package_name: InternalModules
        package_description: "Modules over internal algebras"
        has_HOMALG_IO: true
        ci_additional_packages:
          - homalg_project
          - CAP_project
          - InfiniteLists
          - GradedCategories
        ci_ubuntu_additional_apt_packages:
          - texlive-fonts-extra
        additional_latex_preamble: |
          \usepackage{bbm}
          \DeclareUnicodeCharacter{1D7D9}{\ensuremath{\mathbbm{1}}}
          \DeclareUnicodeCharacter{03C3}{\ensuremath{\sigma}}
          \DeclareUnicodeCharacter{03C1}{\ensuremath{\rho}}
          \DeclareUnicodeCharacter{03BD}{\ensuremath{\nu}}
          \DeclareUnicodeCharacter{03C7}{\ensuremath{\chi}}
    - import_tasks: tasks/package.yml
      vars:
        package_name: GradedCategories
        package_description: "Graded closures of categories"
        has_HOMALG_IO: true
        ci_additional_packages:
          - homalg_project
          - CAP_project
          - InfiniteLists
          - InternalModules
        ci_ubuntu_additional_apt_packages:
          - texlive-fonts-extra
    - import_tasks: tasks/package.yml
      vars:
        package_name: FinSetsForCAP
        package_description: "The elementary topos of (skeletal) finite sets"
        ci_additional_packages:
          - homalg_project
          - CAP_project
          - Toposes
    - import_tasks: tasks/package.yml
      vars:
        package_name: FinGSetsForCAP
        package_description: "The elementary topos of (skeletal) finite G-sets"
        ci_additional_packages:
          - homalg_project
          - CAP_project
          - Toposes
          - FinSetsForCAP
        ci_ubuntu_additional_apt_packages:
          - texlive-science
          - texlive-fonts-extra
        additional_latex_preamble: |
          \usepackage[T1]{fontenc}
          \usepackage[british]{babel}
          \usepackage{microtype}
          \usepackage{amsmath}
          \usepackage{calc}
          \usepackage{amsthm}
          \usepackage{amssymb}
          \usepackage[dvipsnames]{xcolor}
          \usepackage{hyperref}
          \usepackage[linesnumbered,ruled,vlined]{algorithm2e}
          \usepackage{cite}
          \usepackage{url}
          \usepackage{tikz}
          \usetikzlibrary{shapes,arrows,matrix}
          \usepackage{tikz-cd}
          \usepackage{makeidx}
          \usepackage{listings}
          \usepackage[scaled]{beramono}
          \usepackage[figure]{hypcap}
          \renewcommand{\hypcapspace}{2\baselineskip}
          \usepackage{mathtools}
          \usepackage{faktor}
          \DeclareMathOperator{\Stab}{Stab}
          \DeclareMathOperator{\fix}{fix}
          \DeclareMathOperator{\coeq}{coeq}
          \DeclareMathOperator{\im}{im}
          \DeclareMathOperator{\rank}{rank}
          \DeclareMathOperator{\CartProdExt}{CartProdExt}
          \DeclareMathOperator{\End}{End}
          \DeclareMathOperator{\Hom}{Hom}
          \DeclareMathOperator{\op}{op}
          \DeclareMathOperator{\id}{id}
          \DeclareMathOperator{\Obj}{Obj}
          \usepackage{ifthen}
          % use \ell instead of l everywhere
          \mathcode`l="8000
          \begingroup
          \makeatletter
          \lccode`\~=`\l
          \DeclareMathSymbol{\lsb@l}{\mathalpha}{letters}{`l}
          \lowercase{\gdef~{\ifnum\the\mathgroup=\m@ne \ell \else \lsb@l \fi}}%
          \endgroup
    - import_tasks: tasks/meta_package.yml
      vars:
        meta_package_name: CAP_project
        meta_package_description: Categories, Algorithms, and Programming
        ci_additional_packages:
          - homalg_project
        ci_ubuntu_additional_apt_packages:
          - texlive-science
        subpackages:
          - package_name: CAP
            package_description: Categories, Algorithms, Programming
          - package_name: CompilerForCAP
            package_description: Speed up computations in CAP categories
