---
- name: "Ensure {{ pkg_dir }}/{{ package.name }}/.github/workflows/ exists"
  file:
    path: "{{ pkg_dir }}/{{ package.name }}/.github/workflows/"
    state: directory

- name: Tests.yml
  template:
    src: Tests.yml.j2
    dest: "{{ pkg_dir }}/{{ package.name }}/.github/workflows/Tests.yml"
    trim_blocks: false
  vars:
    ci_packages_to_test: "{{ ci_additional_packages_to_test | default([]) }}"

- name: ci_gaprc
  copy:
    src: ci_gaprc
    dest: "{{ pkg_dir }}/{{ package.name }}/ci_gaprc"

- name: .codecov.yml
  template:
    src: .codecov.yml.j2
    dest: "{{ pkg_dir }}/{{ package.name }}/.codecov.yml"

- name: process_coverage_ignored_lines.py
  copy:
    src: process_coverage_ignored_lines.py
    dest: "{{ pkg_dir }}/{{ package.name }}/process_coverage_ignored_lines.py"

- name: upload_codecov.sh
  copy:
    src: upload_codecov.sh
    dest: "{{ pkg_dir }}/{{ package.name }}/upload_codecov.sh"

- name: release-gap-package
  copy:
    src: release-gap-package
    dest: "{{ pkg_dir }}/{{ package.name }}/release-gap-package"
    mode: a+x

- name: make_dist.sh
  template:
    src: make_dist.sh.j2
    dest: "{{ pkg_dir }}/{{ package.name }}/make_dist.sh"
    mode: a+x
