---
- name: "Ensure {{ pkg_dir }}/{{ package.name }}/.github/workflows/ exists"
  file:
    path: "{{ pkg_dir }}/{{ package.name }}/.github/workflows/"
    state: directory

- name: Tests.yml
  template:
    src: Tests.yml.j2
    dest: "{{ pkg_dir }}/{{ package.name }}/.github/workflows/Tests.yml"
    trim_blocks: false
  vars:
    ci_packages_to_test: "{{ [ package.name ] + (ci_additional_packages_to_test | default([])) }}"

- name: .codecov.yml
  template:
    src: .codecov.yml.j2
    dest: "{{ pkg_dir }}/{{ package.name }}/.codecov.yml"

- name: release-gap-package
  copy:
    src: release-gap-package
    dest: "{{ pkg_dir }}/{{ package.name }}/release-gap-package"
    mode: a+x

- name: make_dist.sh
  template:
    src: make_dist.sh.j2
    dest: "{{ pkg_dir }}/{{ package.name }}/make_dist.sh"
    mode: a+x
