---
- name: "Ensure {{ pkg_dir }}/{{ package.name }}/gh-pages/_data/ exists"
  file:
    path: "{{ pkg_dir }}/{{ package.name }}/gh-pages/_data/"
    state: directory

- name: "Ensure {{ pkg_dir }}/{{ package.name }}/gh-pages/_data/package.yml exists"
  file:
    path: "{{ pkg_dir }}/{{ package.name }}/gh-pages/_data/package.yml"
    state: touch
    modification_time: preserve
    access_time: preserve

- name: "Ensure {{ pkg_dir }}/{{ package.name }}/gh-pages/index.md does not exist"
  file:
    path: "{{ pkg_dir }}/{{ package.name }}/gh-pages/index.md"
    state: absent

- name: index.html
  template:
    src: redirect.html.j2
    dest: "{{ pkg_dir }}/{{ package.name }}/gh-pages/index.html"
  vars:
    url: "{% raw %}{{ site.data.package.www }}{% endraw %}"

- name: download_pdf.html
  template:
    src: redirect.html.j2
    dest: "{{ pkg_dir }}/{{ package.name }}/gh-pages/download_pdf.html"
  vars:
    url: "{% raw %}{{ site.data.package.pdf }}{% endraw %}"

- name: view_release.html
  template:
    src: redirect.html.j2
    dest: "{{ pkg_dir }}/{{ package.name }}/gh-pages/view_release.html"
  vars:
    url: "https://github.com/homalg-project/{{ package.name }}/releases/tag/v{% raw %}{{ site.data.package.version }}{% endraw %}"

- name: badge_version.json
  template:
    src: badge.json.j2
    dest: "{{ pkg_dir }}/{{ package.name }}/gh-pages/badge_version.json"
  vars:
    label: "version"
    message: "{% raw %}{{ site.data.package.version }}{% endraw %}"
    color: "orange"

- name: badge_date.json
  template:
    src: badge.json.j2
    dest: "{{ pkg_dir }}/{{ package.name }}/gh-pages/badge_date.json"
  vars:
    message: "{% raw %}{{ site.data.package.date }}{% endraw %}"
