---
- name: Create header
  blockinfile:
    path: ~/index.md
    block: |+
      # {{ meta_package.name }}
      
      {{ meta_package.description }}
      
      | Build Status | Code Coverage |
      | ------------ | ------------- |
      | [![Build Status](https://github.com/homalg-project/{{ meta_package.name }}/workflows/Tests/badge.svg)](https://github.com/homalg-project/{{ meta_package.name }}/actions?query=workflow%3ATests) | {# -#}
        [![Code Coverage](https://codecov.io/gh/homalg-project/{{ meta_package.name }}/branch/master/graph/badge.svg)](https://codecov.io/gh/homalg-project/{{ meta_package.name }}) |
      
    marker: "<!-- {mark} {{ meta_package.name }} HEADER -->"

- name: Include table for subpackages
  include_tasks: tasks/homalg-project.github.io_subpackage_table.yml
  vars:
    packages: "{{ subpackages }}"

- name: Include table for depending packages
  include_tasks: tasks/homalg-project.github.io_used_by_table.yml
  vars:
    packages: "{{ used_by }}"
