---
- name: Import project
  include_tasks: tasks/homalg-project.github.io_project.yml
  vars:
    name: "{{ item.name }}"
    used_by: "{{ item.used_by }}"
  loop: "{{ projects }}"

- name: Import package
  include_tasks: tasks/homalg-project.github.io_package.yml
  vars:
    name: "{{ item.name }}"
  loop: "{{ packages }}"

- name: Import notebook
  include_tasks: tasks/homalg-project.github.io_notebook.yml
  vars:
    url: "{{ item.url }}"
    names: "{{ item.names }}"
  loop: "{{ notebooks }}"
