---
- name: Get PackageInfos
  uri:
    url: https://raw.githubusercontent.com/homalg-project/{{ meta_package.name }}/master/{{ package.name }}/PackageInfo.g
    return_content: yes
  register: PackageInfo_responses
  check_mode: no
  loop: "{{ packages }}"
  loop_control:
    loop_var: package

- name: Initialize packages_enriched
  set_fact:
    packages_enriched: "{{ [] }}"

- name: Set packages_enriched
  set_fact:
    packages_enriched: "{{ packages_enriched + [ zipped[0] | combine( { 'description': zipped[1].content | regex_search('Subtitle := \"[^\"]*') | replace('Subtitle := \"', ''), 'status': zipped[1].content | regex_search('\nStatus := \"[^\"]*') | replace('\nStatus := \"', '') } ) ] }}"
  loop: "{{ packages | zip(PackageInfo_responses.results) | list }}"
  loop_control:
    loop_var: zipped
  no_log: true

- name: Create subpackage table
  blockinfile:
    path: "{{ pkg_dir }}/website/_docs/{{ meta_package.name }}/index.md"
    marker: "<!-- {mark} {{ meta_package.name }} SUBPACKAGES -->"
    block: "{{ lookup('template', 'templates/homalg-project.github.io_subpackage_table.j2') }}"

- name: Create permalink
  template:
    src: homalg-project.github.io_permalink.j2
    dest: "{{ pkg_dir }}/website/permalinks/pkg/{{ package.name }}.html"
  vars:
    path: "pkg/{{ package.name }}"
    url: "https://github.com/homalg-project/{{ meta_package.name }}/tree/master/{{ package.name }}#readme"
  loop: "{{ packages_enriched }}"
  loop_control:
    loop_var: package
