---
- name: Include table for depending packages
  include_tasks: tasks/homalg-project.github.io_package_table.yml
  vars:
    packages: "{{ used_by }}"

- name: Create permalink
  template:
    src: homalg-project.github.io_permalink.j2
    dest: "{{ pkg_dir }}/website/permalinks/prj/{{ name }}.html"
  vars:
    path: "prj/{{ name }}"
    url: "https://github.com/homalg-project/{{ name }}#readme"
