---
- name: Get PackageInfos
  uri:
    url: https://raw.githubusercontent.com/homalg-project/{{ package.name }}/master/PackageInfo.g
    return_content: yes
  register: PackageInfo_responses
  check_mode: no
  loop: "{{ packages }}"
  loop_control:
    loop_var: package

- name: Check if HTML docu is available
  uri:
    url: https://homalg-project.github.io/{{ package.name }}/doc/chap0_mj.html
  register: HTML_responses
  failed_when: HTML_responses.status is not defined
  check_mode: no
  loop: "{{ packages }}"
  loop_control:
    loop_var: package

- name: Initialize packages_enriched
  set_fact:
    packages_enriched: "{{ [] }}"

- name: Set packages_enriched
  set_fact:
    packages_enriched: "{{ packages_enriched + [ zipped[0] | combine( { 'description': zipped[1].content | regex_search('Subtitle := \"[^\"]*') | replace('Subtitle := \"', ''), 'status': zipped[1].content | regex_search('\nStatus := \"[^\"]*') | replace('\nStatus := \"', ''), 'has_docu': zipped[2].status == 200 } ) ] }}"
  loop: "{{ packages | zip(PackageInfo_responses.results, HTML_responses.results) | list }}"
  loop_control:
    loop_var: zipped
  no_log: true

- name: Create depending package table
  blockinfile:
    path: "{{ pkg_dir }}/website/_docs/{{ meta_package.name }}-based/index.md"
    marker: "<!-- {mark} {{ meta_package.name }} USED_BY -->"
    block: "{{ lookup('template', 'templates/homalg-project.github.io_used_by_table.j2') }}"

- name: Create permalink
  template:
    src: homalg-project.github.io_permalink.j2
    dest: "{{ pkg_dir }}/website/permalinks/pkg/{{ package.name }}.html"
  vars:
    path: "pkg/{{ package.name }}"
    url: "https://github.com/homalg-project/{{ package.name }}#readme"
  loop: "{{ packages_enriched }}"
  loop_control:
    loop_var: package
