---
- name: Get PackageInfos
  uri:
    url: https://raw.githubusercontent.com/homalg-project/{{ meta_package.name }}/master/{{ package.name }}/PackageInfo.g
    return_content: yes
  register: PackageInfo_responses
  check_mode: no
  loop: "{{ packages }}"
  loop_control:
    loop_var: package

- name: Check if HTML docu is available
  uri:
    url: https://homalg-project.github.io/{{ meta_package.name }}/{{ package.name }}/doc/chap0_mj.html
  register: HTML_responses
  failed_when: HTML_responses.status is not defined
  check_mode: no
  loop: "{{ packages }}"
  loop_control:
    loop_var: package

- name: Check if PDF docu is available
  uri:
    url: https://raw.githubusercontent.com/homalg-project/{{ meta_package.name }}/doc/{{ package.name }}.pdf
  register: PDF_responses
  failed_when: PDF_responses.status is not defined
  check_mode: no
  loop: "{{ packages }}"
  loop_control:
    loop_var: package

- name: Initialize packages_enriched
  set_fact:
    packages_enriched: "{{ [] }}"

- name: Set packages_enriched
  set_fact:
    packages_enriched: "{{ packages_enriched + [ zipped[0] | combine( { 'description': zipped[1].content | regex_search('Subtitle := \"[^\"]*') | replace('Subtitle := \"', ''), 'status': zipped[1].content | regex_search('Status := \"[^\"]*') | replace('Status := \"', ''), 'has_html_docu': zipped[2].status == 200, 'has_pdf_docu': zipped[3].status == 200 } ) ] }}"
  loop: "{{ packages | zip(PackageInfo_responses.results, HTML_responses.results, PDF_responses.results) | list }}"
  loop_control:
    loop_var: zipped
  no_log: true

- name: Create subpackage table
  blockinfile:
    path: ~/index.md
    marker: "<!-- {mark} {{ meta_package.name }} SUBPACKAGES -->"
    block: "{{ lookup('template', 'templates/homalg-project.github.io_subpackage_table.j2') }}"
