---
- name: Check if GitHub Pages are available for this project
  uri:
    url: https://homalg-project.github.io/{{ meta_package.name }}/{{ item.name }}/PackageInfo.g
  register: gh_pages_responses
  failed_when: gh_pages_responses.status is not defined
  check_mode: no
  loop: "{{ subpackages }}"

- name: Set meta_package_enriched
  set_fact:
    meta_package_enriched: "{{ meta_package | combine( { 'path': meta_package.name } ) }}"

- name: Initialize subpackages_enriched
  set_fact:
    subpackages_enriched: "{{ [] }}"

- name: Set subpackages_enriched
  set_fact:
    subpackages_enriched: "{{ subpackages_enriched + [ item[0] | combine( { 'path': meta_package.name + '/' + item[0].name, 'has_gh_pages': item[1].status == 200 } ) ] }}"
  loop: "{{ subpackages | zip(gh_pages_responses.results) | list }}"

- import_tasks: tasks/README.md.yml
  vars:
    package: "{{ meta_package_enriched }}"
    doc_packages: "{{ subpackages_enriched }}"
    is_meta_package: true

- import_tasks: tasks/ci.yml
  vars:
    package: "{{ meta_package_enriched }}"
    pdf_doc_packages: "{{ subpackages_enriched | selectattr('has_gh_pages', 'equalto', false) | list }}"

- name: Import subpackage
  include_tasks: tasks/package_common.yml
  vars:
    package: "{{ item }}"
  loop: "{{ subpackages_enriched }}"
