---
- name: Set meta_package_enriched
  set_fact:
    meta_package_enriched: "{{ meta_package | combine( { 'path': meta_package.name } ) }}"

- name: Initialize subpackages_enriched
  set_fact:
    subpackages_enriched: "{{ [] }}"

- name: Set subpackages_enriched
  set_fact:
    subpackages_enriched: "{{ subpackages_enriched + [ item | combine( { 'path': meta_package.name + '/' + item.name, 'repo': meta_package.name, 'docu_only': item.docu_only|default(false), 'GAPDoc_docu': item.GAPDoc_docu|default(false), 'tests_without_precompiled_code': item.tests_without_precompiled_code|default(false), 'has_notebooks': (pkg_dir | expanduser + '/' + meta_package.name + '/' + item.name + '/examples/notebooks/') is directory } ) ] }}"
  loop: "{{ subpackages }}"
  no_log: true

- import_tasks: tasks/README.md.yml
  vars:
    package: "{{ meta_package_enriched }}"
    doc_packages: "{{ subpackages_enriched }}"
    is_meta_package: true

- name: Metapackage makefile
  blockinfile:
    path: "{{ pkg_dir }}/{{ meta_package.name }}/makefile"
    marker: "# {mark} PACKAGE JANITOR"
    block: "{{ lookup('template', 'templates/meta_package_makefile.j2') }}"
  vars:
    doc_packages: "{{ subpackages_enriched }}"

- import_tasks: tasks/gh-pages.yml
  vars:
    package: "{{ meta_package_enriched }}"
    is_meta_package: true

- name: Initialize ci_additional_repositories_enriched
  set_fact:
    ci_additional_repositories_enriched: "{{ ci_additional_repositories | default([]) }}"

- name: Prepend needed_other_repositories of subpackages to ci_additional_repositories_enriched
  set_fact:
    ci_additional_repositories_enriched: "{{ (item.needed_other_repositories | default([])) + ci_additional_repositories_enriched }}"
  loop: "{{ subpackages_enriched }}"
  no_log: true

- name: Remove duplicates from ci_additional_repositories_enriched
  set_fact:
    ci_additional_repositories_enriched: "{{ ci_additional_repositories_enriched | unique }}"

- import_tasks: tasks/ci.yml
  vars:
    package: "{{ meta_package_enriched }}"
    doc_packages: "{{ subpackages_enriched }}"
    is_meta_package: true

- name: Import subpackage
  include_tasks: tasks/package_common.yml
  vars:
    package: "{{ item }}"
  loop: "{{ subpackages_enriched }}"
