---
- name: Check if GitHub Pages are available for this project
  uri:
    url: https://homalg-project.github.io/{{ package_name }}/PackageInfo.g
  register: gh_pages_response
  failed_when: gh_pages_response.status is not defined
  check_mode: no

- import_tasks: tasks/ci.yml
  vars:
    pdf_doc_packages: "{{ [] if gh_pages_response.status == 200 else [ {'package_name': package_name} ] }}"

- import_tasks: tasks/package_common.yml
  vars:
    package_path: "{{ package_name }}"
    has_gh_pages: "{{ gh_pages_response.status == 200 }}"
