---
- name: PackageInfo.g PackageName
  lineinfile:
    path: "{{ pkg_dir }}/{{ package_name }}/PackageInfo.g"
    regexp: "PackageInfo :="
    line: 'PackageName := "{{ package_name }}",'

- name: PackageInfo.g License
  lineinfile:
    path: "{{ pkg_dir }}/{{ package_name }}/PackageInfo.g"
    regexp: "License :="
    line: 'License := "GPL-2.0-or-later",'

- name: PackageInfo.g Date
  lineinfile:
    path: "{{ pkg_dir }}/{{ package_name }}/PackageInfo.g"
    regexp: "Date :="
    line: 'Date := Concatenation( ~.Version{[ 9, 10 ]}, "/", ~.Version{[ 6, 7 ]}, "/", ~.Version{[ 1 .. 4 ]} ),'

- name: PackageInfo.g SourceRepository.URL
  lineinfile:
    path: "{{ pkg_dir }}/{{ package_name }}/PackageInfo.g"
    regexp: "^    URL := "
    line: '    URL := Concatenation( "https://github.com/homalg-project/", ~.PackageName ),'

- name: PackageInfo.g PackageWWWHome
  lineinfile:
    path: "{{ pkg_dir }}/{{ package_name }}/PackageInfo.g"
    regexp: "PackageWWWHome  := "
    line: 'PackageWWWHome  := Concatenation( "https://homalg-project.github.io/", ~.PackageName ),'

- name: PackageInfo.g PackageDoc.BookName
  lineinfile:
    path: "{{ pkg_dir }}/{{ package_name }}/PackageInfo.g"
    regexp: "^  BookName  := "
    line: '  BookName  := "{{ package_name }}",'

- name: PackageInfo.g PackageDoc.LongTitle
  lineinfile:
    path: "{{ pkg_dir }}/{{ package_name }}/PackageInfo.g"
    regexp: "^  LongTitle := "
    line: '  LongTitle := "{{ package_description }}",'

- name: README.md header
  blockinfile:
    path: "{{ pkg_dir }}/{{ package_name }}/README.md"
    insertbefore: BOF
    marker: "<!-- {mark} HEADER -->"
    block: |
      # {{ package_name }} – {{ package_description }}

      | **Documentation**                        | **Build Status**                                             |
      |:----------------------------------------:|:------------------------------------------------------------:|
      | [![][docs-stable-img]][docs-stable-url]  | [![][tests-img]][tests-url] [![][codecov-img]][codecov-url]  |

- name: README.md footer
  blockinfile:
    path: "{{ pkg_dir }}/{{ package_name }}/README.md"
    insertafter: EOF
    marker: "<!-- {mark} FOOTER -->"
    block: |
      [docs-stable-img]: https://img.shields.io/badge/docs-stable-blue.svg
      [docs-stable-url]: https://homalg-project.github.io/{{ package_name }}/doc/chap0.html

      [tests-img]: https://github.com/homalg-project/{{ package_name }}/workflows/Tests/badge.svg
      [tests-url]: https://github.com/homalg-project/{{ package_name }}/actions?query=workflow%3ATests

      [codecov-img]: https://codecov.io/gh/homalg-project/{{ package_name }}/branch/master/graph/badge.svg
      [codecov-url]: https://codecov.io/gh/homalg-project/{{ package_name }}

- name: init.g header
  replace:
    path: "{{ pkg_dir }}/{{ package_name }}/init.g"
    regexp: "\\A(.*\n){5}"
    replace: |
      #
      # {{ package_name }}: {{ package_description }}
      #
      # Reading the declaration part of the package.
      #

- name: read.g header
  replace:
    path: "{{ pkg_dir }}/{{ package_name }}/read.g"
    regexp: "\\A(.*\n){5}"
    replace: |
      #
      # {{ package_name }}: {{ package_description }}
      #
      # Reading the implementation part of the package.
      #

- name: PackageInfo.g header
  replace:
    path: "{{ pkg_dir }}/{{ package_name }}/PackageInfo.g"
    regexp: "\\A(.*\n){8}"
    replace: |
      #
      # {{ package_name }}: {{ package_description }}
      #
      # This file contains package meta data. For additional information on
      # the meaning and correct usage of these fields, please consult the
      # manual of the "Example" package as well as the comments in its
      # PackageInfo.g file.
      #

- name: "{{ item }} header"
  replace:
    path: "{{ item }}"
    regexp: "\\A(.*\n){5}"
    replace: |
      #
      # {{ package_name }}: {{ package_description }}
      #
      # Declarations
      #
  with_fileglob: "{{ pkg_dir }}/{{ package_name }}/gap/*.gd"

- name: "{{ item }} header"
  replace:
    path: "{{ item }}"
    regexp: "\\A(.*\n){5}"
    replace: |
      #
      # {{ package_name }}: {{ package_description }}
      #
      # Implementations
      #
  with_fileglob: "{{ pkg_dir }}/{{ package_name }}/gap/*.gi"

- name: 000_LoadPackage.tst
  template:
    src: 000_LoadPackage.tst.j2
    dest: "{{ pkg_dir }}/{{ package_name }}/tst/000_LoadPackage.tst"

- name: LICENSE
  template:
    src: LICENSE.j2
    dest: "{{ pkg_dir }}/{{ package_name }}/LICENSE"

- name: makedoc.g
  template:
    src: makedoc.g.j2
    dest: "{{ pkg_dir }}/{{ package_name }}/makedoc.g"
    trim_blocks: false

- name: makedoc_with_overfull_hbox_warnings.g
  template:
    src: makedoc_with_overfull_hbox_warnings.g.j2
    dest: "{{ pkg_dir }}/{{ package_name }}/makedoc_with_overfull_hbox_warnings.g"
    trim_blocks: false

- name: makefile
  template:
    src: makefile.j2
    dest: "{{ pkg_dir }}/{{ package_name }}/makefile"

- name: testall.g
  template:
    src: testall.g.j2
    dest: "{{ pkg_dir }}/{{ package_name }}/tst/testall.g"

- name: Tests.yml
  template:
    src: Tests.yml.j2
    dest: "{{ pkg_dir }}/{{ package_name }}/.github/workflows/Tests.yml"
    trim_blocks: false

- name: .codecov.yml
  template:
    src: .codecov.yml.j2
    dest: "{{ pkg_dir }}/{{ package_name }}/.codecov.yml"

- name: .gitignore
  template:
    src: .gitignore.j2
    dest: "{{ pkg_dir }}/{{ package_name }}/.gitignore"
