---
- name: Set package_enriched
  set_fact:
    package_enriched: "{{ package | combine( { 'path': package.name, 'docu_only': package.docu_only|default(false) } ) }}"

- import_tasks: tasks/ci.yml
  vars:
    package: "{{ package_enriched }}"
    ci_additional_repositories_enriched: "{{ (package.needed_other_repositories | default([])) + (ci_additional_repositories | default([])) }}"
    is_meta_package: false

- import_tasks: tasks/gh-pages.yml
  vars:
    package: "{{ package_enriched }}"
    is_meta_package: false

- import_tasks: tasks/package_common.yml
  vars:
    package: "{{ package_enriched }}"
